[theme]
primaryColor="#C19A6B"              # Gold (buttons, highlights from logo)
backgroundColor="#0B0C10"           # Deep, almost black blue (matches logo)
secondaryBackgroundColor="#1F2833"  # Soft dark blue for cards/widgets
textColor="#C5C6C7"                 # Soft light grey (readable on dark bg)
font="sans serif"
