[theme]
primaryColor="#C19A6B"              # Gold (for buttons, highlights)
backgroundColor="#0B1A2A"           # Deep, Dark Blue (main background)
secondaryBackgroundColor="#13293D"  # Slightly lighter blue for sidebars/cards
textColor="#F5DEB3"                 # Light Wheat/Gold Text
font="sans serif"
